baseURL: https://incjjung.netlify.app/
languageCode: en
DefaultContentLanguage: en
title: Inchul page
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Inchul
  customCss: []
  customJs: []
  description: From DS to DE
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/profile2.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/inchul-jung-612000bb/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/incjung/
    - icon: fab fa-twitter
      title: fa-twitter
      url: https://twitter.com/inczzung
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:incjjung@gmail.com
  title: Inchul
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 300
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 400
