---
title: "오늘도 공부중 .. Bayesrulesbook.com"
date: 2022-07-17T11:38:53+12:00
draft: false
tags: ["devops", "data-engineering", "kubernetes"]
---

* 베이지안니즘
아직도 미련을 못버리고 기회가 될때마다 찾아보는 주제 중에 하나가 베이지안이다. 개인적으로 이를 이해하기 위해서 한국에서 샀던 책이 몇권 된다.

통계학 전공자들을 위한 책들이 전부였어서, 읽을 때마다 힘들었던 기억이 난다.

사실 나는 이론적 배경 지식 보다는 실제 적용을 어떻게 하는지가 관심이 더 있는데, 이론적으로 분석하고 증명하는 수식이 나열된 서적들은 필요하 없었다.


그래서 조금더 응용되었던 사례 책으로 ``Data Analysis'' 주제에 책을 ~원서~로 구매 했었다. 거의 10만원 상당의 원서는 재미있는 사례 중심으로 분석을 해 보여주는 책들이었는데, 사실 이는 `내 수준'에 비해 너무 나간면이 있었다.
이를 이해하기 위해서는 어느 정도의 기반 지식이 필요했는데, 이들의 타깃 독자가 `나'는 아니었던 것이다.

이론적 배경과 응용하고 적용하는 중간 어디 쯤에 있는 사람에게 맞는 교재가 필요한데, 사실 찾기기 쉽지 않았다. 그러다 최근 ~Udemy~에서 강의도 하나 보고, 그를 통해서 확률 모형을 만드는데 도움이 되는 `네트워크'도 알게 되었고, 오늘 말할 아주 좋은 사이트도 발견할 수 있었다.

https://www.bayesrulesbook.com

어떻게 알게된 사이트인지는 나도 기억이 나지 않는다. 이런저럭 베이지안 관련 검색을 하다 우연히 들어가게 된 것 같다. 아무 분명히 그 전에도 몇번 들어가 보지 않았을까? 그때는 내가 아직 준비가 되지 않아 좋은 컨텐츠인데도 알아보지 못했을 것이다.

알아야 보이는 것들인거다.

* 구슬도 엮어야 보배
이런 지식들을 이해하기 위해서는 주변 지식들이 필요하고 그 주변 주식을 하느로 엮어서 알고 있어야 한다. 결국 이론도 필요하고 적용 기술도 필요하다 이 사이에 보이지 않은 많은 파편의 기술들이 필요하고.

이런 면에서 하나를 알기위해서 단순히 하나만 안다고 해서 안다고 할 수는 없는 것이다. 결국 아는 것에 있어서 불필요한 것은 없나보다. 그러니 계속 머리속에 무언가를 넣을려고 노력하는 것은 의미있는 노력이다.



