---
title: "no idea"
date: 2022-04-28T15:10:32+12:00
draft: false
---

* Emacs 로 놀고 일하기
  예전에는 매일 emacs로 일정 정리하고 기술 노트도 만들고 파일 편집이나 코딩도 많이 했었는데, 요즘은 모들 툴들이 특징들이 있고 사용하기 편하게 나와서 예전만큼 많이 쓰지는 않는다.
  너무 안쓰는 것 같아서 오랜만에 Emacs를 열어 봤다. 그러고 보니 emacs로 블로그를 편집하고 싶었는데 그때는 아는 것도 없고 Rstudio로 md 포맷으로 잘 쓰고 있었기 때문에 굳이 시간 들여가면 인터넷을 헤매고 싶지 않았다. 그래서 나중에 해 볼 todo 중에 하나로 남겨 두었었는데, 오늘이 그날이다. emace에서 분명히 hugo를 지원하는 패키지가 있을 것으로 판단하고 구글링 해보니, 역시나 바로 easy-hugo 패키지 링크가 떠버리네.

  Rstudio로 md타입과 Rmd 타입으로 R을 실행하고 코드도 쉽게 넣을 수 있기 때문에 주로 사용했었는데, 최근에는 R로 쓰는 일이 많지가 않다보니 블로그를 쓰지도 않게 되었다. 뭐 대단한 내용을 쓰는 것도 아니고 주로 문단 구분이나 리스팅 정도만 되면 되니깐 md 문법으로 대부분 필요한 기능은 쓰고 있다. 

  하지만 오랜만에 Emacs를 킨 이상 *org-mode* 를 이용해서 블로그를 쓸 수도 있다면 왠지 조금이라도 블로그를 더 쓰려고 하지 않을까? 지금까지는 R코딩을 하지 않아도 Rstudio를 켜서 md파일로 작성을 하고 컴파일을 했는데, 간단한 잡담이나 글만 쓸꺼면 그냥 Emacs에서 끝내버릴 수 있으니깐 그리고 *org-mode* 문법이 더 쉬우니깐 더 자주 쓰게 되지 않을까?

  근데 md포맷으로 할때는 잘 컴파일 되서 보이던 글이 왜 org에서는 안나오는지 모르겠다.
  그래다가 헤더를 좀보니 헤더가 뭔가 draft라는 기분 나쁜 단어가 있다. 이걸 *false*로 하니 그때서야 컴파일이 되서 글이 보이기 시작한다.
  #+BEGIN_SRC bash
    title: "no idea"
    date: 2022-04-28T15:10:32+12:00
    draft: true
  #+END_SRC

  이거 링크를 찾아봐도 안나오더니 그냥 깜으로 해보니 된다. 후후
  https://github.com/masasam/emacs-easy-hugo

  더 써봐야 겠다. 
  

