---
title: "My Bucket List"
date: 2023-01-16T13:27:31+13:00
draft: false
tags: ["emacs", "org-mode", "elisp", "productivity"]
---

It's hard to fill out 100 items. Here are my bucket list from 2022-04-29 to 2023-9-06. Maybe I can achive some or not. 

We achieved a lot of things in my life. but I don't like to stay this spot. wanto to keep pushing myself forward to. 

* bucket list
  1) 영어사람 친구와 철학적 탐구와 인문적 지식을 교류할 정도의 영어 실력
  2) 이정도의 대화를 할 수 있을 만한 영어 사람
  3) 영어 드리마 무비 무제한 자유 시청
  4) 유럽 순방 (독일,오스트리아,이태리,로마,스페인,파리) 2 달 
  5) 태국 가족 럭셔리 가족 여행 2주일
  6) 베트남 여행 2 주일
  7) fiji 여행
  8) 요트 타고 여행
  9) Distinguished Technologist/ 전문가 그룹 일원 되기
  10) tatoo - design - do
  11) 내집 테라스나 뒷마당 가지기
  12) 전기차 가지기
  13) tracking with my girls
  14) 25억 자산
  15) 1등석 타기
  16) 2등석 타기(비즈니스)
  17) 전공하나 더하기
  18) 전문 지식 책 집필하기
  19) youtube 실시간
  20) youtube 구독자 100k 
  21) 인기 블로그 작가 인플루엔서
  22) 커뮤니티 운영
  23) 멘토 멘티
  24) 날 존경하는 사람 10명 만들기
  25) 인도인 요가 수업
  26) 꾸준한 취미라 할 수 있는 거 갖기 - 달리기
  27) 호주에서 직장
  28) 영국에서 직장
  29) 싱가포르에서 직장
  30) 한국과 뉴질랜드에 각각 집
  31) 뉴질 남섬 길게 여행
  32) trip with only wife
  33) 매장 운영
  34) 자서전
  35) 강연하기
  36) 맥라인 기계
  37) 내방 연구실 갖기
  38) 서울과 외국 돌아가면서 살기 약 3~4개월씩
  39) emacs editor 개발하기
  40) 언어로 기똥찬거 개발하고 공유하기
  41) 개인 클라우드 서버
  42) 전자 회로 공부 하고 개발
  43) 철학적 토론과 독서 모임
  44) 명상
  45) 마라톤 도전하기 20km
  46) 마라톤 도전하기 42.195 km
  47) 호주 영주권
  48) 수화 하기
  49) 애플 전제품
  50) 아이들이 존경하는 아빠되기
  51) 
           
* done list
  1) 기계식 키보드
  2) 영주권 성공
  3) youtube 방송하기

