---
title: "2023 09 11 Modifying a Emacs Theme a Bit [Elisp]"
date: 2023-09-11T09:35:28+12:00
draft: false
tags: ["emacs", "org-mode", "elisp", "productivity"]
---

* New Emacs

Recently, I have finally installed new ~Emacs29~ to use new features.
Wait, I am sorry, it's lie. To be honest, I don't know the whole new features
I think we don't need to know all of them at all, and cannot use all of them. right?

I use a Emacs as text editer for many file format and generate a report with Latex via ~org mode~.
Additionaly, Emacs is managing my knowledge. It's great work. 

So, I configured only some featues and done them in my ~init.el~.
Perfect!!

* Theme
One thing I don't like it from Emacs is the default outlook. only white background.
I am not happy with that. So as always, I need to chage the theme.

At this time, I found a very cool theme, called *NANO*.
- https://github.com/rougier/nano-theme

Go and see the screenshots in the home page. is't cool?

What about you? You have a lot of options to change your ~Emacs~ *theme*. You know that  Emacs includes some great themes by default. you can give a try all of them, and choose one of them.

You don't like them? no worries, you can google like "Emacs theme".

No matter what you find, I highly recommend to use opensouce theme. Mostly, they are cool, it prevents you from wasting your time to identfy the best color combination for your Emacs theme.

Do you like hacking on Emacs? No problem, you can create your own theme. Go for it. I know there are many good tutorials on internet.

To me, I will not do it. Because there are alreay tons of themes out in the world I haven't tred.

The *NANO* theme was installed and I am happy, and can't be happy no more.

* But, ...

During short peroid of my experience of the theme, I found a unconventional stuff to me. When I use highlight to region, the backgound color is not enough to do contrast between backgound and the highighted words.

Maybe that's only me who complain it. At leate, I hated.

At this point, I must decide whether I 1) endured it or 2) changed the theme or 3) modifed a bit of the theme (only the part I hated).

I love the simplicity of the theme and the dark color combination. Furdermore, so choosed option 3).

To be clear, I don't like to study the whole theme code directly, I am lazy.

My plan is overwriting the highlight part from the NANO theme. Then, I don't need to look into the theme code directly. 

* Overwrting the highlight
Firstly, I need to know a concept of ~Face~ in Emacs.
- Emacs face: https://www.gnu.org/software/emacs/manual/html_node/emacs/Faces.html

#+begin_example
Emacs can display text in several different styles, called faces. Each face can specify various face attributes, such as the font, height, weight, slant, foreground and background color, and underlining or overlining. 
#+end_example

Let's do research a bit in google and youtube as always.
 - The highlight is a face of =region=.
 - ~set-face-attribute~ function can overwriting the face. (check the fuction description with ~C-h f~)

For instance, try this for RED highlight. 
#+begin_src elisp
  (set-face-attribute 'region nil
                      :background "red")

#+end_src

or can try underline when you highlight
#+begin_src elisp
  (set-face-attribute 'region nil
                      :underline "white")

#+end_src

