---
title: "My Tulsa King ViewPoint"
date: 2025-02-27T13:32:09+13:00
draft: false
tags: ["personal", "life", "reflection"]
---

=Tulsa King=

* 주요 인물
- 실베스터 스탤론 (두목)
- 개릿 헤들런드 (눈에 띄는 놈)  

* 줄거리
주인공(드와이트 맨프레디)은 자신이 속한 뉴욕 갱 조직을 위해 오랜 기간동안 교도소 수감생활을 마치고 돌아온다. 그러나 갱단은 그가 그리 반갑지만은 않다. 자신들에게 위협적인 존재가 될것이라는 두려움이 있었던 것일까. 결국 여러 이유를 대고 그를 Tulsa로 보내버리게 된다. 드와이트는 아무 연고 없는 Tulsa에서, 맨 바닥에서 부터 스스로 세력을 키워가며 본인만의 family를 성장 시킨다. 이 과정에서 기존에 토착 세력과 충돌도 벌어지고, 갑자기 나타난 그를 FBI에서는 주의 깊게 감시하게 된다. 예상외로 성장을 거듭하는 그의 존재는 뉴욕 갱단 뿐만이 아니라 기존의 영향력을 행사하던 세력들에게 걱정거리도 되어 간다.

* 개인감상
남자 냄새 물씬 풍기는 시리즈, 실베스터 스탤론의 특유한 건들거리는 걸음걸이와 Tulsa의 거친 느낌의 도시가 잘 어울린다. 중간 중간에 올드 무비에서 나오던 카우보이 영화 음악을 리메이크한 배경음이 이러한 분위기를 더욱 잘 어울리게 만들어준다. 총격신과 액션신이 있지만 과하지 않고, 잔인하지 않게 처리하여서 부담없이 감상할 수 있다. 잔인한 만할 장면은 피가 튀기는 정도로 마무리 한다. 

트와이트가 돈을 버는 방식은 이해 관계자와 싸워 그들의 것을 탈취하는 것뿐이다. 드와이트의 조직 구성을 할때 왜 그들이 선택되어 져야 하는지와 어떤 점이 그들이 드와이트와 합류하게 되는지 이해가 안된다. 그래서 인지 이야기를 만들어 내는 구성원들의 관계 구성도는 복잡하지 않지만, 상하 관계가 아무런 계기 없이 바뀌곤 해서, 집중도가 떨어진다. 

선과 악의 싸움이 아니라 악과 악의 싸움이 주이며, 가끔씩 선량한 사람들이 지나가는 정도로 보인다. 액션 장르라기 보다는, 람보였던, 실베스터 스탤론이 노익장을 선보이는 장르. 예전의 람보나 록키를 보는 정도의 즐거음이 있다. 그가 늙었다는 생각도 들지만, 저 근육을 아직까지도 간직하고 있다는 것도 대단하네 하며 감상하게 되는 시리즈 물이다.

2편까지는 악과 악의 싸움이지만, 2편 마지막편에서는, 3편이 나온다면 정부기관이 그를 이용해서 더 나쁜 놈들을 처리하는 식의 시리즈가 나올것 처럼 마무리를 한다. 

