---
title: "Emacs My Startup Page"
date: 2024-12-24T10:05:07+13:00
draft: false
---

* 나만의 시작 화면 
emacs 를 시작 하면 기본으로 보여지는 시작 화면이 있다. emace 로고, 소개글과 함께 링크들이 보여진다. 습관적으로 키고 끄다 보니 별 문제 없이 사용해 오다. 언제 부터인지는 모르겠지만 시작하면 매번 반복되는 나만의 패턴이 생기게 되고, 내가 항상 시작하는  화면이 처음부터 띄어지면 좋겠다는 생각을 하게 됐다.

그러나, 항상 그렇듯이 막연한 생각에 이런저런 elisp 함수를 찾아보다 못찾고 덮어두고 있었다. 포기라기 보단, 그냥 마음속에 구석에 쳐박아두면, 대부분, 불연듯 다시 떠오르고, 여기저기 인터넷 기사나 유튜브 바다를 다니다 보면 관련된 글이나, 영상을 통해 영감을 얻게되기 때문에, 그때 다시 시작하면 된다. 아마 처음에는 찾아야 하는 적절한 용어를 모르거나 당시의 내 이해나 지식이 모자르기 때문일 것이다.

어째든, 최근에 관련 기사를 하나 읽게 되었고, 거기서 영감을 얻어서 드디어 나만의 시작 화면을 설정할 수 있게 되었다.

나만의 시작화면을 띄우기 위해서는, 우선 기 기본 화면이 안나오게 해야 한다.
관련 변수가 ~inhibit-startup-screen~ and ~emacs-strtup-hook~ 이다.
- ~inhibit-startup-screen~: This is for use in your personal init file. Original value was nil, Non-nil inhibits the startup screen.
- ~emacs-strtup-hook~: Normal hook run after loading init files and handling the command line.
hook 변수는 ~add-hook~ 함수로 init file에서 걸어주어야 한다.

* 나의 시작화면
내 경우는 처음 emacs를 띄우자 마자 거의 ~org-agenda-list~ 를 띄워 스케쥴이나 나의 할일들을 확인한다. 그리고 중간중간 완료한 작업을 표시하거나 필요하면 새로운 작업 타스크들을 추가 한다. 보통은 새로운 뭔가를 추가하는 것 보다는 항상 잊지 말아야 할 것을 리만인드 해주기 때문에 자주 agenda buffer를 자주 불러와 보곤 한다.

그래서 나의 시작화면으로 ~org-agenda-list~ 를 띄우기로 결정했다. 여기서 약간의 기본 agenda-list의 옵션을 바꿔준다. 기본 일주일 리스트를 보여주지만 나는 4일의 리스트를 보이기로 결정했다. 이는  ~org-agenda-span~ 를 고쳐주면 된다. Original value was 'week'. 

추가로 나는 ~calendar~ 를 함께 보여주기로 했다. 그러면 코드는 이렇게 된다. 

#+begin_src elisp 
  (setq org-agenda-span 4)
  (setq inhibit-startup-screen t)
  (add-hook 'emacs-startup-hook
            (lambda ()
              (let ((buffer-agenda "*Org Agenda*")
                    (buffer-calendar "*Calendar*")
                    )
                (org-agenda-list)
                (delete-other-windows)
                (calendar)
            )))
#+end_src

간단히 코드 설명을 해보면, 
When ~inhibit-startup-screen~ is not nil, you can define your own start up screen. with ~emacs-startup-hook~, you can compose your buffers which are org-agendar-list and calendar in my case.

FYI, ~delete-other-windows~ is to delete the current buffer. Becasue the agendar-list and calendar buffers are created on current buffer, you need to delete the first buffer once you create agendar buffer or calendar buffer.




