---
title: "Good Life Definition 주저리"
date: 2024-09-27T16:23:08+12:00
draft: false
---

* 유전적으로 다른 사람인데 왜 다 같은 목표 같은 길을 가야 하지?
인권은 평등하다고 해도, 모든 인간의 성질이 똑같지 않다. 그러다 보면 개성이 분명히 존재하고 다른 장담점을 각기 갖을 수 밖에 없다. 그렇지만, 통일된 시각에서 평가를 받아야하는 사회 구조 안에서 자라오다보니 그 틀이 영원히 벗어 날 수 없는 운명이라 받아들이곤 한다. 결국에는 정해진 순위안에 들어가지 못하면, 그 사회구조에 적응 못한 인간이 되고, 낙오자라는 낙인을 찍게 된다. 그 사회 구조에서의 실패일 뿐인데, 인생의 패배자가 된거 처럼 생각되어진다.

그 구조에서 한발짝 정도 비껴서 서보자. 내가 새로운 구조를 만들어서 나에게 적용해 보자. 남들과는 다른 목표를 그 구조의 목적지라고 생각해보자. 바보나라에서 천재가 될 수도 있고, 천재 나라의 바보가 될 수도 있지만, 천재 나라와 바보 나라를 둘다 걸쳐서 살 수 있으면, 남들과 다른 내 목적을 세울 수 있지 않을까.

* 왜 사냐 보단 무엇을 위해 사냐
왜 살까라는 고민을 주로 해온 나지만, 중요한 질문을 빼먹지 않았을까? 내가 선택해서 세상에 나온 것이 아니니, 왜 태어났는지를 나 스스로 찾을 수는 없다. 이미 벌어진 일이니 그져 살아져가는 거다. 그러다 보니 사는 이유나 목적을 스스로 찾기 보다는 저절로 정해져 버리게 된다. 모난 돌이 정을 맞는 다고 체화되어 스스로 모나기 보단 남들과 비슷하게 살면서 눈에 띄지 않고 너무 뒤떨어지려고도 하지 않는게 미덕이라 생각하고 산다.

보편적인 성공 스토리를 주워 담게 되고, 그러다 보니 그 속에 공통적인 부분이 바로 인생의 목적이나 지향점이 되어 버리게 된다.
건강하고 행복한 삶은 기본이고, 여유롭고 풍족하며, 남들보다는 조금 더 많이 금전적이이거나 권력적인 무언가를 가져야지 잘 살아가는 거라는 생각이 정착되고 만다.

사실 목적이 뭐냐에 따라 여러가지 갈래길을 찾아 갈 수 있는데, 남들과 똑같은 기준으로 사고를 하다보니, 남들 모두 가고 있는 길을 따라 가게 되며, 어느 순간 이 길이 왜 나에게는 벅차고 힘들지 하며 한숨을 내 쉬게 된다.

* 그럼 나는
나는 새롭게 목적지를 정하겠다. 사는 이유도 내가 정하겠다.
나는 건강하게 늙어가며, 쪼들리지 않는 삶 중에서 스스로를 멋있다고 생각할 수 있는 것들을 계속해서 찾아가며 살고 싶다.


