---
title: "My Bucket List"
date: 2023-01-16T13:22:34+12:00
draft: false
---

It's hard to fill out 100 items. Here are my bucket list from 2022-04-29 to 2023-01-06. Maybe I can achive some or not. 

We achieved a lot of things in my life. but I don't like to stay this spot. wanto to keep pushing myself forward to. 

* bucket list
  1) 영어사람 친구와 철학적 탐구와 인문적 지식을 교류할 정도의 영어 실력
  2) 이정도의 대화를 할 수 있을 만한 영어 사람
  3) 영어 드리마 무비 무제한 자유 시청
  4) 유럽 순방 (독일,오스트리아,이태리,로마,스페인,파리) 30일정도
  5) 태국 가족 럭셔리 가족 여행 2주일
  6) 베트남 여행 2 주일
  7) 요트 타고 여행
  8) Distinguished Technologist/ 전문가 그룹 일원 되기
  9) tatoo - design - do
  10) 내집 테라스나 뒷마당 가지기
  11) 전기차 가지기
  12) tracking with my girls
  13) 25억 자산
  14) 1등석 타기
  15) 2등석 타기(비즈니스)
  16) 전공하나 더하기
  17) 전문 지식 책 집필하기
  18) 방송하기
  19) 인기 블로그 작가 인플루엔서
  20) 커뮤니티 운영
  21) 멘토 멘티
  22) 날 존경하는 사람 10명 만들기
  23) 인도인 요가 수업
  24) 꾸준한 취미라 할 수 있는 거 갖기
  25) 호주에서 직장
  26) 영국에서 직장
  27) 싱가포르에서 직장
  28) 한국과 뉴질랜드에 각각 집
  29) 뉴질 남섬 길게 여행
  30) trip with only wife
  31) 매장 운영
  32) 자서전
  33) 전문 책쓰기
  34) 맥라인 기계
  35) 내방 연구실 갖기
  36) 서울과 외국 돌아가면서 살기 약 3~4개월씩
  37) emacs editor 개발하기
  38) 언어로 기똥찬거 개발하고 공유하기
  39) 애플 전제품
  40) 개인 클라우드 서버
  41) 전자 회로 공부 하고 개발
  42) 철학적 토론과 독서 모임
  43) 운동과 명상으로 건강한 정신과 육체
  44) 
      
  
      
* done list
  1) 기계식 키보드
  2) 영주권 성공
